# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 21:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160207_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 7, 21, 41, 15, 990000, tzinfo=utc)),
        ),
    ]
